name: rc4
version: 0.1.4
author: Delaney Gillilan <delaneygillilan@gmail.com>
description: Implementation of RC4-Drop algorithm.
homepage: http://pub.dartlang.org/packages/rc4
environment:
  sdk: '>=1.0.0'
dependencies:
  crypto: '>=0.9.0'
  range: '>=1.1.0'
  unittest: '>=0.9.2'
